@include header.yml

version: 2.1

@def early_return_for_forked_pull_requests
early_return_for_forked_pull_requests:
  description: >-
    If this build is from a fork, stop executing the current job and return success.
    This is useful to avoid steps that will fail due to missing credentials.
  steps:
    - run:
       name: Early return if this build is from a forked PR
        command: |
          if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
            echo "Nothing to do for forked PRs, so marking this step successful"
            circleci step halt
          fi
@end

defaults:
  default_jobs: &default_jobs
    - centos
    - ubuntu

commands:
  abort_for_docs:
    steps:
      - run:
          name: Avoid tests for docs
          command: |
            if [[ $CIRCLE_BRANCH == *_docs ]]; then
              echo "Identifies as documents PR, no testing required"
              circleci step halt
            fi

  {{early_return_for_forked_pull_requests}}

  ci_steps:
    steps:
      - abort_for_docs
      - checkout
      - run:
          name: Get Dependencies
          command: ./.circleci/ci_get_deps.sh
      - run:
          name: Build
          command: bash -l -c "./.circleci/ci_build.sh"
      - run:
          name: Test
          command: bash -l -c "./.circleci/ci_test.sh"
      - run:
          name: Package
          command: bash -l -c "COMPAT_DIR=$BUILD_DIR make pack"
          environment:
            - PACKAGE_NAME: redisearch-oss
      - early_return_for_forked_pull_requests
      - persist_to_workspace:
          root: artifacts
          paths:
            - '*.zip'
            - '*.tgz'
            - snapshots/*.zip
            - snapshots/*.tgz


@include jobs.yml
@include conditions.yml
# @include conditions.yml
@def jojo
@end

workflows:
  version: 2

  default_flow:
    jobs:
      - ubuntu:
          <<: *on-any-branch
      - centos:
          <<: *on-any-branch
      - macos:
          <<: *on-version-tags
      - debug_asan:
          <<: *on-any-branch
      - debug_msan:
          <<: *on-any-branch
      - coverage:
          context: common
          <<: *on-any-branch
      - deploy_snapshots:
          context: common
          requires: *default_jobs
          <<: *on-integ-and-version-tags
      - deploy_release:
          context: common
          requires: *default_jobs
          <<: *on-version-tags

  nightly:
    triggers:
      - schedule:
          cron: "20 17 * * *"
          filters:
            branches:
              only: master
    jobs:
      - macos
@include header.yml

version: 2.1

@def early_return_for_forked_pull_requests
early_return_for_forked_pull_requests:
  description: >-
    If this build is from a fork, stop executing the current job and return success.
    This is useful to avoid steps that will fail due to missing credentials.
  steps:
    - run:
       name: Early return if this build is from a forked PR
        command: |
          if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
            echo "Nothing to do for forked PRs, so marking this step successful"
            circleci step halt
          fi
@end

defaults:
  default_jobs: &default_jobs
    - centos
    - ubuntu

commands:
  abort_for_docs:
    steps:
      - run:
          name: Avoid tests for docs
          command: |
            if [[ $CIRCLE_BRANCH == *_docs ]]; then
              echo "Identifies as documents PR, no testing required"
              circleci step halt
            fi

  {{early_return_for_forked_pull_requests}}

  ci_steps:
    steps:
      - abort_for_docs
      - checkout
      - run:
          name: Get Dependencies
          command: ./.circleci/ci_get_deps.sh
      - run:
          name: Build
          command: bash -l -c "./.circleci/ci_build.sh"
      - run:
          name: Test
          command: bash -l -c "./.circleci/ci_test.sh"
      - run:
          name: Package
          command: bash -l -c "COMPAT_DIR=$BUILD_DIR make pack"
          environment:
            - PACKAGE_NAME: redisearch-oss
      - early_return_for_forked_pull_requests
      - persist_to_workspace:
          root: artifacts
          paths:
            - '*.zip'
            - '*.tgz'
            - snapshots/*.zip
            - snapshots/*.tgz


@include jobs.yml
@include conditions.yml
# @include conditions.yml
@def jojo
@end

workflows:
  version: 2

  default_flow:
    jobs:
      - ubuntu:
          <<: *on-any-branch
      - centos:
          <<: *on-any-branch
      - macos:
          <<: *on-version-tags
      - debug_asan:
          <<: *on-any-branch
      - debug_msan:
          <<: *on-any-branch
      - coverage:
          context: common
          <<: *on-any-branch
      - deploy_snapshots:
          context: common
          requires: *default_jobs
          <<: *on-integ-and-version-tags
      - deploy_release:
          context: common
          requires: *default_jobs
          <<: *on-version-tags

  nightly:
    triggers:
      - schedule:
          cron: "20 17 * * *"
          filters:
            branches:
              only: master
    jobs:
      - macos
# autor: Avital Fine
# date: 30.03.2021

version: 2.1

@def early_return_for_forked_pull_requests
early_return_for_forked_pull_requests:
  description: >-
    If this build is from a fork, stop executing the current job and return success.
    This is useful to avoid steps that will fail due to missing credentials.
  steps:
    - run:
       name: Early return if this build is from a forked PR
        command: |
          if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
            echo "Nothing to do for forked PRs, so marking this step successful"
            circleci step halt
          fi
@end

defaults:
  default_jobs: &default_jobs
    - centos
    - ubuntu

commands:
  abort_for_docs:
    steps:
      - run:
          name: Avoid tests for docs
          command: |
            if [[ $CIRCLE_BRANCH == *_docs ]]; then
              echo "Identifies as documents PR, no testing required"
              circleci step halt
            fi

  {{early_return_for_forked_pull_requests}}

  ci_steps:
    steps:
      - abort_for_docs
      - checkout
      - run:
          name: Get Dependencies
          command: ./.circleci/ci_get_deps.sh
      - run:
          name: Build
          command: bash -l -c "./.circleci/ci_build.sh"
      - run:
          name: Test
          command: bash -l -c "./.circleci/ci_test.sh"
      - run:
          name: Package
          command: bash -l -c "COMPAT_DIR=$BUILD_DIR make pack"
          environment:
            - PACKAGE_NAME: redisearch-oss
      - early_return_for_forked_pull_requests
      - persist_to_workspace:
          root: artifacts
          paths:
            - '*.zip'
            - '*.tgz'
            - snapshots/*.zip
            - snapshots/*.tgz


jobs:
  ubuntu:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    environment:
      - BUILD_DIR: build-debian
    steps:
      - ci_steps
      - store_artifacts:
          path: build-debian/logs

  centos:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-centos7
    environment:
      - BUILD_DIR: build-el
    steps:
      - ci_steps
      - store_artifacts:
          path: build-el/logs

  macos:
    macos:
      xcode: 11.3.0
    environment:
      - BUILD_DIR: build-macos
    steps:
      - ci_steps
      - store_artifacts:
          path: build-macos/logs

  deploy_snapshots:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - abort_for_docs
      - early_return_for_forked_pull_requests
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Deploy Snapshots to S3
          command: |
            cd ~/workspace/snapshots
            for f in *.zip *.tgz; do
              aws s3 cp $f s3://redismodules/$PACKAGE_NAME/snapshots/ --acl public-read
            done

  debug_asan:
    docker:
      - image: redisfab/clang:12-x64-stretch
    steps:
      - abort_for_docs
      - checkout
      - run:
          name: Run & build tests
          command: bash -l -c "ASAN=1 ./.circleci/ci_diag_san12.sh"
          no_output_timeout: 20m
      - store_artifacts:
          path: build-asan/logs

  debug_msan:
    docker:
      - image: redisfab/clang:12-x64-stretch
    steps:
      - abort_for_docs
      - checkout
      - run:
          name: Run & build tests
          command: bash -l -c "MSAN=1 ./.circleci/ci_diag_san12.sh"
          no_output_timeout: 20m
      - store_artifacts:
          path: build-msan/logs

  coverage:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - abort_for_docs
      - checkout
      - run:
          name: Build & Test
          command: bash -l -c "./.circleci/ci_coverage.sh"
          no_output_timeout: 20m
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_artifacts:
          path: build-coverage/logs

  deploy_release:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - abort_for_docs
      - early_return_for_forked_pull_requests
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Deploy Releases to S3
          command: |
            cd ~/workspace
            for f in *.zip *.tgz; do
              aws s3 cp $f s3://redismodules/$PACKAGE_NAME/ --acl public-read
            done

# @include conditions.yml
@def jojo
@end

workflows:
  version: 2

  default_flow:
    jobs:
      - ubuntu:
          <<: *on-any-branch
      - centos:
          <<: *on-any-branch
      - macos:
          <<: *on-version-tags
      - debug_asan:
          <<: *on-any-branch
      - debug_msan:
          <<: *on-any-branch
      - coverage:
          context: common
          <<: *on-any-branch
      - deploy_snapshots:
          context: common
          requires: *default_jobs
          <<: *on-integ-and-version-tags
      - deploy_release:
          context: common
          requires: *default_jobs
          <<: *on-version-tags

  nightly:
    triggers:
      - schedule:
          cron: "20 17 * * *"
          filters:
            branches:
              only: master
    jobs:
      - macos
# autor: Avital Fine
# date: 30.03.2021

version: 2.1

@def early_return_for_forked_pull_requests
early_return_for_forked_pull_requests:
  description: >-
    If this build is from a fork, stop executing the current job and return success.
    This is useful to avoid steps that will fail due to missing credentials.
  steps:
    - run:
       name: Early return if this build is from a forked PR
        command: |
          if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
            echo "Nothing to do for forked PRs, so marking this step successful"
            circleci step halt
          fi
@end

defaults:
  default_jobs: &default_jobs
    - centos
    - ubuntu

commands:
  abort_for_docs:
    steps:
      - run:
          name: Avoid tests for docs
          command: |
            if [[ $CIRCLE_BRANCH == *_docs ]]; then
              echo "Identifies as documents PR, no testing required"
              circleci step halt
            fi

  {{early_return_for_forked_pull_requests}}

  ci_steps:
    steps:
      - abort_for_docs
      - checkout
      - run:
          name: Get Dependencies
          command: ./.circleci/ci_get_deps.sh
      - run:
          name: Build
          command: bash -l -c "./.circleci/ci_build.sh"
      - run:
          name: Test
          command: bash -l -c "./.circleci/ci_test.sh"
      - run:
          name: Package
          command: bash -l -c "COMPAT_DIR=$BUILD_DIR make pack"
          environment:
            - PACKAGE_NAME: redisearch-oss
      - early_return_for_forked_pull_requests
      - persist_to_workspace:
          root: artifacts
          paths:
            - '*.zip'
            - '*.tgz'
            - snapshots/*.zip
            - snapshots/*.tgz


jobs:
  ubuntu:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    environment:
      - BUILD_DIR: build-debian
    steps:
      - ci_steps
      - store_artifacts:
          path: build-debian/logs

  centos:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-centos7
    environment:
      - BUILD_DIR: build-el
    steps:
      - ci_steps
      - store_artifacts:
          path: build-el/logs

  macos:
    macos:
      xcode: 11.3.0
    environment:
      - BUILD_DIR: build-macos
    steps:
      - ci_steps
      - store_artifacts:
          path: build-macos/logs

  deploy_snapshots:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - abort_for_docs
      - early_return_for_forked_pull_requests
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Deploy Snapshots to S3
          command: |
            cd ~/workspace/snapshots
            for f in *.zip *.tgz; do
              aws s3 cp $f s3://redismodules/$PACKAGE_NAME/snapshots/ --acl public-read
            done

  debug_asan:
    docker:
      - image: redisfab/clang:12-x64-stretch
    steps:
      - abort_for_docs
      - checkout
      - run:
          name: Run & build tests
          command: bash -l -c "ASAN=1 ./.circleci/ci_diag_san12.sh"
          no_output_timeout: 20m
      - store_artifacts:
          path: build-asan/logs

  debug_msan:
    docker:
      - image: redisfab/clang:12-x64-stretch
    steps:
      - abort_for_docs
      - checkout
      - run:
          name: Run & build tests
          command: bash -l -c "MSAN=1 ./.circleci/ci_diag_san12.sh"
          no_output_timeout: 20m
      - store_artifacts:
          path: build-msan/logs

  coverage:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - abort_for_docs
      - checkout
      - run:
          name: Build & Test
          command: bash -l -c "./.circleci/ci_coverage.sh"
          no_output_timeout: 20m
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_artifacts:
          path: build-coverage/logs

  deploy_release:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - abort_for_docs
      - early_return_for_forked_pull_requests
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Deploy Releases to S3
          command: |
            cd ~/workspace
            for f in *.zip *.tgz; do
              aws s3 cp $f s3://redismodules/$PACKAGE_NAME/ --acl public-read
            done

# @include conditions.yml
@def jojo
@end

workflows:
  version: 2

  default_flow:
    jobs:
      - ubuntu:
          <<: *on-any-branch
      - centos:
          <<: *on-any-branch
      - macos:
          <<: *on-version-tags
      - debug_asan:
          <<: *on-any-branch
      - debug_msan:
          <<: *on-any-branch
      - coverage:
          context: common
          <<: *on-any-branch
      - deploy_snapshots:
          context: common
          requires: *default_jobs
          <<: *on-integ-and-version-tags
      - deploy_release:
          context: common
          requires: *default_jobs
          <<: *on-version-tags

  nightly:
    triggers:
      - schedule:
          cron: "20 17 * * *"
          filters:
            branches:
              only: master
    jobs:
      - macos
